version: 0.2

env:
  variables:
    SONAR_SCANNER_VERSION: "7.2.0.5079"

phases:
  install:
    commands:
      - echo "Installing Sonar Scanner..."
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip \
          https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH

  build:
    commands:
      - echo "Running SonarQube Analysis..."
      - sonar-scanner
          -Dsonar.projectKey=duledjordjevic_streamio
          -Dsonar.organization=duledjordjevic
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
          -Dsonar.qualitygate.wait=true
          -Dsonar.ws.timeout=300

reports:
  sonar-report:
    files:
      - "**/*"
